### ISSUE TITLE
Doc inconsistencies / confusions

### ISSUE THREAD

**Issue by viridia** [internalfx/rethinkdb-regrid#17]
I'm having a hard time understanding the docs. For example, the text refers to 'id', 'fileId' and 'filename' and it's not clear which should be used in which context. For example, createWriteStream() accepts a filename, but createReadStream() wants an id. If id is different than a filename, then how do I find what is the id of the file that I just wrote?

Also, the docs refer to functions like 'upload' which apparently no longer exist.

**Comment by internalfx** [comment]
Thanks for pointing this out...

I have made recent strides to vastly simplify the API.
Some methods have been removed, and that was likely the source of the confusion.

These are the methods you will most likely want.

```
    writeFile,
    getFile,
    readFile
```

`createWriteStream` and `createReadStream` are actually used by the above methods and are "lower level" functions.

I provide access to them so devs have a way to stream data if needed (like if the files are very large).

now for your filename question....

Files with the same name are considered revisions.
You can save a multiple files with the same name. And the `filename` field is required. So I have to have it in order to write your file to the database. So, `createWriteStream` has to have a filename.

Since multiple files can have the same name, getting a read stream from `createReadStream` must use an id, So that Regrid knows exactly which file revision to load.

Typically you would first make a call to `getFile` before calling `createReadStream`, That will get you the ID you want.

**Comment by internalfx** [comment]
Also I have updated the docs

**Comment by internalfx** [comment]
If you use a UUID for the filename you do not need to keep a reference to the _actual_ id.

Also filenames can be anything `/username/topic/filename.jpg`.

That's not applicable to your project, just wanted to give you ideas.

`getFile` is _very_ fast, don't hesitate to use the method as often as you need it. If a file is looked up multiple times it won't event make the trip to the DB.

For a small set of heavily used files, Regrid is faster than disk in my testing.

This is due to the fact that Regrid will hold buffers and metadata in ram.

**Comment by internalfx** [comment]
> I don't want different users who upload images with the same name to overwrite each other's images. Thus, if user A uploads 'foo.png', this has no relation to any other 'foo.png' that might have been uploaded by a different user. That's why I use a UUID for the filename, to avoid those collisions.)

If you are returning Id's this is not a problem anyway. You can store the original filename. The filename field  can be useful for giving the user the original name when they download it later.

Two files with the same name DO NOT ever overwrite each other. They only _appear_ to _if_ you look up a file by it's filename (make sense?). You can always lookup any file throughout Regrid history by it's ID.

The filename is basically just a convenience. just think of it as a piece of data describing the file, and as one of a few possible ways of finding a file, that's it.

**Comment by internalfx** [comment]
This is why the `getFile` function can take and `id` _or_ a `filename`, you get to pick :smile:

**Comment by internalfx** [comment]
Also calling `getFile` right before `createReadStream` incurs almost no penalty.

Even though they are separate calls with separate promises, one will resolve instantly.

After the first `getFile` call the data for `createReadStream` is now cached in memory.

Regrid was designed so I could be lazy, so don't work too hard for performance. :wink:

**Comment by viridia** [comment]
Wow, that's a lot of follow-up comments :)

Just in case you are curious as to what I am working on: https://github.com/viridia/vortex

**Comment by internalfx** [comment]
Just wanted you to fully understand the internals, cool project.
